[package]
name = "QuadbTech"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"       # For SHA-256 hashing
serde = { version = "1.0", features = ["derive"] }  # For serialization & deserialization
serde_json = "1.0"  # For JSON formatting
